name = "starlet"
version = "1.0.1"
description = "An LLM interaction library that makes you feel like a star"
licences = ["MIT"]
repository = { type = "github", user = "jtdowney", repo = "starlet" }

[dependencies]
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
jscheam = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
birdie = ">= 1.5.3 and < 2.0.0"
envoy = ">= 1.1.0 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
unitest = ">= 1.0.0 and < 2.0.0"
